{% extends "template.phtml" %}

{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h4>Aset Monitor &rang; Tambah Aset</h4>
            <p>Sementara hanya suport untuk monitoring asset yang kerupiah</p>
            <hr/>
            <form action="/save-aset" method="post" class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-sm-1">Aset</label>
                    <div class="col-sm-2">
                        <select name="coin" class="form-control input-sm">
                            {% for c in coin %}
                                <option value="{{ c['id'] }}">{{ c['label'] }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <label class="control-label col-sm-1">H.beli</label>
                    <div class="col-sm-2">
                        <input type="text" name="hbeli" class="form-control input-sm number" required/>
                    </div>
                    <label class="control-label col-sm-1">Jumlah</label>
                    <div class="col-sm-2">
                        <input type="text" name="jml_aset" class="form-control input-sm numberbtc" required/>
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-sm btn-default">Simpan</button>
                    </div>
                </div>
            </form>
            {% if (aset) %}
            <hr/>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th class="text-center">ASET</th>
                        <th class="text-center">H.BELI</th>
                        <th class="text-center">JML.ASET</th>
                        <th class="text-center">MODAL</th>
                        <th class="text-center">H.SEKARANG</th>
                        <th class="text-center">ASET.SEKARANG</th>
                        <th class="text-center">PROFIT/LOSS</th>
                        <th class="text-center">#</th>
                    </tr>
                </thead>
                <tbody>
                    {% set tmodal=0 %}
                    {% for as in aset %}
                        <tr>
                            <td><i class="cc {{ as['name'] }}"></i> {{ as['label'] }}</td>
                            <td class="money text-right">{{ as['hbeli'] }}</td>
                            <td class="text-right moneycoin">{{ as['jml'] }}</td>
                            <td class="money text-right" data-modal="{{ as['modal'] }}">{{ as['modal'] }}</td>
                            <td class="vharga harga_{{ as['kode'] }} text-right" data-value=""></td>
                            <td class="vmodal modal_{{ as['kode'] }} text-right"></td>
                            <td class="vlaba laba_{{ as['kode'] }} text-right"></td>
                            <td class="text-center">
                                <a href="/delete-asset/{{ as['id'] }}"><span class="glyphicon glyphicon-trash"></span></a>
                            </td>
                        </tr>
                        {% set tmodal = (tmodal+as['modal']) %}
                    {% endfor %}
                    <tr>
                        <td colspan="3">TOTAL PERKIRAAN ASET IDR</td>
                        <td class="money text-right" id="tmodal" data-modal="{{ tmodal }}">{{ tmodal }}</td>
                        <td></td>
                        <td class="money text-right" id="taset">0</td>
                        <td class="money text-right" id="tlaba">0</td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ parent() }}
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <script src="/lib/monitoraset.js"></script>
    <script>
        $(function(){
            $("td.money").number(true);
            var cx = $("td.moneycoin").text();
            $("td.moneycoin").number(true,8)
        })
    </script>
{% endblock %}