{% extends "template.phtml" %}

{% block body %}

    <div class="row">
        <div class="col-sm-12">
            <h4 class="text-center">Live Chat dari <a href="https://vip.bitcoin.co.id" target="_blank">https://vip.bitcoin.co.id</a></h4>
            <p class="text-center text-danger">Chat ini hanya berupa viewer untuk hiburan semata, anda tidak bisa membalas chat,<br/>Jika ingin membalas chat silahkan gunakan website resmi Bitcoin Indonesia</p>
        </div>
        <div class="col-lg-12 col-md-12 col-xs-12">
            <div id="chat">

            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
    {{ parent() }}
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <script src="/lib/livechat.js"></script>
{% endblock %}
