{% extends "template.phtml" %}

{% block body %}

    <div class="row">
        <div class="col-sm-12 col-lg-12 col-sm-12">
            <h4><i class="cc {{ row['name'] }}"></i> {{ row['label'] }} &rang; Bitcoin Indonesia</h4>
            <table class="table table-striped table-bordered">
                <tr>
                    <td class="text-center">Last</td>
                    <td class="text-center">Low</td>
                    <td class="text-center">High</td>
                </tr>
                <tr>
                    <td class="text-center strong" id="last_price"></td>
                    <td class="text-center strong" id="low_price"></td>
                    <td class="text-center strong" id="high_price"></td>
                </tr>
            </table>
            <div id="chartnya"></div>
            <p>
                <a href="https://indodax.com/chart/{{ row.id }}" target="_blank" class="btn btn-sm btn-default">Advanced Chart</a>
            </p>
        </div>
    </div>

{% endblock %}

{% block script %}
    {{ parent() }}
    <script src="https://indodax.com/js/highstocks-4.2.5/highstock-all.js"></script>
    <script src="https://indodax.com/js/highstocks-4.2.5/modules/exporting.js"></script>
    <script src="https://indodax.com/js/highstocks-4.2.5/modules/indicators/js/indicators.js"></script>
    <script src="https://indodax.com/js/highstocks-4.2.5/modules/indicators/js/sma.js"></script>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <script>
        var parameter = "tradedata-{{ row['id'] }}";
        var key = "{{ row['id'] }}";
        var labelnya ="{{ row['label'] }}";
        var jenis ="{{ row['exc'] }}";
        var coin = "{{ mcoin['id'] }}";
        var uri = "{{ mcoin['uri'] }}";
        var lbl = "{{ mcoin['label'] }}";
        var jenis = "{{ row['exc'] }}"
    </script>
    <script src="/lib/details.js"></script>
{% endblock %}
