{% extends "template.phtml" %}

{% block body %}

    <div class="row">
        <div class="col-sm-12 col-lg-5 col-sm-12">
            <h4><i class="cc {{ row['name'] }}"></i> {{ row['label'] }} &rang; Bitcoin Indonesia</h4>
            <table class="table table-striped table-bordered">
                <tr>
                    <td class="text-center">Last</td>
                    <td class="text-center">24.h</td>
                    <td class="text-center">Low</td>
                    <td class="text-center">High</td>
                </tr>
                <tr>
                    <td class="text-center strong" id="last_price"></td>
                    <td class="text-center strong" id="change"></td>
                    <td class="text-center strong" id="low_price"></td>
                    <td class="text-center strong" id="high_price"></td>
                </tr>
            </table>
            <div id="chartnya"></div>
            <p>
                <a href="https://vip.bitcoin.co.id/chart/{{ row.id }}" target="_blank" class="btn btn-sm btn-default">Advanced Chart</a>
            </p>
        </div>
        <div class="col-sm-12 col-lg-7 col-sm-12">
            <h4><i class="cc {{ row['name'] }}"></i> {{ row['label'] }} &rang; Around The Exchanger</h4>
            <div class="row">
                <div class="col-lg-6 col-sm-12">
                    <table class="table">
                        <tr>
                            <td colspan="2" class="text-muted">coinmarketcap.com</td>
                        </tr>
                        <tr>
                            <td id="marketkap-price" colspan="2" class="strong"></td>
                        </tr>
                        <tr>
                            <td id="marketkap-change1h" class="text-left strong"></td>
                            <td id="marketkap-change24h" class="text-right strong"></td>
                        </tr>
                    </table>
                </div>
                {% for ex in exchange %}
                <div class="col-lg-6 col-sm-12" id="{{ ex }}">
                    <table class="table">
                        <tr>
                            <td colspan="2" class="text-muted">{{ ex }}</td>
                        </tr>
                        <tr>
                            <td id="{{ ex }}-price" colspan="2" class="strong"></td>
                        </tr>
                        <tr>
                            <td id="{{ ex }}-change1h" class="text-left strong"></td>
                            <td id="{{ ex }}-change24h" class="text-right strong"></td>
                        </tr>
                    </table>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
    {{ parent() }}
    <script src="https://vip.bitcoin.co.id/js/highstocks-4.2.5/highstock-all.js"></script>
    <script src="https://vip.bitcoin.co.id/js/highstocks-4.2.5/modules/exporting.js"></script>
    <script src="https://vip.bitcoin.co.id/js/highstocks-4.2.5/modules/indicators/js/indicators.js"></script>
    <script src="https://vip.bitcoin.co.id/js/highstocks-4.2.5/modules/indicators/js/sma.js"></script>
    <script src="https://vip.bitcoin.co.id/js/highstocks-4.2.5/modules/indicators/js/bb.js"></script>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <script> 
        var parameter = "tradedata-{{ row['id'] }}";
        var key = "{{ row['id'] }}";
        var labelnya ="{{ row['label'] }}";
        var jenis ="{{ row['exc'] }}";
        var coin = "{{ mcoin['id'] }}";
        var uri = "{{ mcoin['uri'] }}";
        var lbl = "{{ mcoin['label'] }}";
        var idr = {{ idr|raw }};
    </script>
    <script src="/lib/details.js"></script>
    <script src="/lib/details-external.js"></script>
    <script>
        $(document).ready(function(){
            {% for exc in  exchange %}
                CryptoCompareApi('{{ exc }}');
            {% endfor %}

            setInterval(function(){
                    MarketKap();
                    {% for exc in  exchange %}
                        CryptoCompareApi('{{ exc }}');
                    {% endfor %}
            }, 60000);
        });
    </script>
{% endblock %}