{% extends "template.phtml" %}

{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <p>Auto Gembel Monitoring untuk melihat perkembangan harga crypto currencies, Sumber utama diambil dari <a href="https://vip.bitcoin.co.id" target="_blank">vip.bitcoin.co.id</a><br/> dan beberapa data lainya diambil dari public api yang tersedia, seperti: 
                <ol>
                    <li><a href="https://www.cryptocompare.com/api" target="_blank">CryptoCompare</a></li>
                    <li><a href="https://coinmarketcap.com/api/" target="_blank">CoinmarketCap</a></li>
                </ol>
            </p>
            <p>Ini merupakan <strong>projek kurang-kerjaan</strong>, jika anda merasa isinya tidak sesuai dengan yang anda harapkan <strong>jangan komplain</strong><br/>Jika anda mau sourcesnya silahkan download di <a href="#" target="_blank">Auto Gembel Github</a></p>

            <p>Website ini dibangun menggunakan:
            <ol>
                <li><a href="https://www.slimframework.com" target="_blank">PHP Slim Framework</a></li>
                <li><a href="https://github.com/slimphp/Twig-View" target="_blank">Twig-View</a></li>
                <li><a href="https://getbootstrap.com" target="_blank">Bootstrap 3.3</a></li>
                <li><a href="https://github.com/allienworks/cryptocoins" target="_blank">Cryptocoin WebFonts</a></li>
            </ol>
            </p>
        </div>
    </div>
{% endblock %}